class Countries:
    armenia = "Армения"
    belorussia = "Белорусь"
    vietnam = "Вьетнам"
    germany = "Германия"
    georgia = "Грузия"
    india = "Индия"
    indonesia = "Индонезия"
    spain = "Испания"
    italy = "Италия"
    kazahstan = "Казахстан"
    kyrgizia = "Киргизия"
    uae = "ОАЭ"
    serbia = "Сербия"
    tailand = "Таиланд"
    turkey = "Туркция"
    ukraine = "Украина"
    finland = "Финляндий"
    french = "Франция"
    montenegro = "Черногория"
    czechia = "Чехия"
    sri_lanka = "Шри Ланка"
    other = "Другая"

